version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v3.4.2 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1 
    ports:
      - "9100:9100"
    restart: unless-stopped

  nginx:
    image: nginx:1.18.0
    volumes:
      - ./nginx_logs:/var/log/nginx
    ports:
      - "80:80"

  apache:
    image: httpd:2.4.64
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./apache_logs:/usr/local/apache2/logs
    ports:
      - "81:80"

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yaml
      - ./nginx_logs:/var/log/nginx
      - ./apache_logs:/usr/local/apache2/logs
    command: ["-config.file=/etc/promtail/config.yaml"]

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafanadata:/var/lib/grafana

  loki:
    image: grafana/loki:3.5.2
    ports:
      - "3100:3100"

volumes:
  grafanadata: {}